Fix parsing for namespace flags
rook/kubectl-rook-ceph pull request #113
Opened 2023-05-24 18:07 UTC by BlaineEXE

Namespace flags should be parsed by the parent command and not by child
    commands. This poses a particular problem for the 'ceph' and 'rbd'
    commands, as they normally have flag parsing disabled. The parent
    command should use the cobra.Command option 'TraverseChildren' in order
    to parse parent args before parsing child commands.
    
This is built on top of #112

2023-05-25 04:48 UTC, subhamkrai requested changes
one suggestion: 
later in this file could you modify the flags to 
```
RootCmd.PersistentFlags().StringVarP(&OperatorNamespace, "operator-namespace", "o","rook-ceph", "Kubernetes namespace where rook operator is running")
RootCmd.PersistentFlags().StringVarP(&CephClusterNamespace, "namespace", "n","rook-ceph", "Kubernetes namespace where ceph cluster is created")
```

and one question:
with these changes should we remove `DisableFlagParsing: true,` for other commands or we should have it like it is currently as I don't see any harm in keeping it. Thoughts?

2023-05-25 15:41 UTC, BlaineEXE commented
I would suggest not making a shorthand for --operator-namespace. `-o` is often used for `--output`, and assuming to keep that trend would probably be best. Most users won't have a different operator namespace, and so I think it's okay to not give it a shorthand.

2023-05-25 16:15 UTC, travisn commented
> I would suggest not making a shorthand for --operator-namespace. `-o` is often used for `--output`, and assuming to keep that trend would probably be best. Most users won't have a different operator namespace, and so I think it's okay to not give it a shorthand.

We may want to keep `-o` for compatibility with the existing script options.

2023-05-31 04:23 UTC, subhamkrai commented
@BlaineEXE could you look at above comment

2023-05-31 15:55 UTC, subhamkrai approved these changes
Based on offline discussion, approving.

2023-05-31 21:10 UTC, merged

2023-06-02 05:46 UTC, subhamkrai commented
fixes #101