restore-crd: use dynamic api to get k8s resource
rook/kubectl-rook-ceph pull request #221
Opened 2024-01-08 09:42 UTC by subhamkrai

currently, we are directly using `kubectl` command to get crds, crd name and also for other ops. Since, we now have code to get k8s resource using dynamic api, let's use that instead of `kubectl` command.

**Description of your changes:**

**Which issue is resolved by this Pull Request:**
Resolves #

**Checklist:**

- [ ] **Commit Message Formatting**: Commit titles and messages follow guidelines in the [developer guide](https://rook.io/docs/rook/latest/Contributing/development-flow/#commit-structure).
- [ ] Reviewed the developer guide on [Submitting a Pull Request](https://rook.io/docs/rook/latest/Contributing/development-flow/#submitting-a-pull-request)
- [ ] CI tests has been updated, if necessary.
- [ ] Documentation has been updated, if necessary.
- [ ] Unit tests have been added, if necessary.

2024-01-08 09:43 UTC, subhamkrai commented
This require more local testing

2024-01-10 11:19 UTC, subhamkrai commented
local testing

```yaml
./bin/kubectl-rook-ceph restore-deleted cephclusters my-cluster
Warning: rook version 'rook: v1.13.0-alpha.0.152.g107567406' is running a pre-release version of Rook.

Info: Detecting which resources to restore for crd "cephclusters"
Info: Restoring CR my-cluster
Warning: The resource my-cluster was found deleted. Do you want to restore it? yes | no

yes
Info: Proceeding with restoring deleting CR
Info: Scaling down the operator
Info: Backing up kubernetes and crd resources
Info: Deleting validating webhook rook-ceph-webhook if present
Info: Removing ownerreferences from resources with matching uid 63e9a0ea-49c1-4091-9e24-d88ef684081d
Info: Removing owner references for secret cluster-peer-token-my-cluster
Info: Removed ownerReference for Secret: cluster-peer-token-my-cluster

Info: Removing owner references for secret rook-ceph-admin-keyring
Info: Removed ownerReference for Secret: rook-ceph-admin-keyring

Info: Removing owner references for secret rook-ceph-config
Info: Removed ownerReference for Secret: rook-ceph-config

Info: Removing owner references for secret rook-ceph-crash-collector-keyring
Info: Removed ownerReference for Secret: rook-ceph-crash-collector-keyring

Info: Removing owner references for secret rook-ceph-exporter-keyring
Info: Removed ownerReference for Secret: rook-ceph-exporter-keyring

Info: Removing owner references for secret rook-ceph-mgr-a-keyring
Info: Removed ownerReference for Secret: rook-ceph-mgr-a-keyring

Info: Removing owner references for secret rook-ceph-mons-keyring
Info: Removed ownerReference for Secret: rook-ceph-mons-keyring

Info: Removing owner references for secret rook-csi-cephfs-node
Info: Removed ownerReference for Secret: rook-csi-cephfs-node

Info: Removing owner references for secret rook-csi-cephfs-provisioner
Info: Removed ownerReference for Secret: rook-csi-cephfs-provisioner

Info: Removing owner references for secret rook-csi-rbd-node
Info: Removed ownerReference for Secret: rook-csi-rbd-node

Info: Removing owner references for secret rook-csi-rbd-provisioner
Info: Removed ownerReference for Secret: rook-csi-rbd-provisioner

Info: Removing owner references for configmaps rook-ceph-mon-endpoints
Info: Removed ownerReference for configmap: rook-ceph-mon-endpoints

Info: Removing owner references for service rook-ceph-exporter
Info: Removed ownerReference for service: rook-ceph-exporter

Info: Removing owner references for service rook-ceph-mgr
Info: Removed ownerReference for service: rook-ceph-mgr

Info: Removing owner references for service rook-ceph-mgr-dashboard
Info: Removed ownerReference for service: rook-ceph-mgr-dashboard

Info: Removing owner references for service rook-ceph-mon-a
Info: Removed ownerReference for service: rook-ceph-mon-a

Info: Removing owner references for deployment rook-ceph-mgr-a
Info: Removed ownerReference for deployment: rook-ceph-mgr-a

Info: Removing owner references for deployment rook-ceph-mon-a
Info: Removed ownerReference for deployment: rook-ceph-mon-a

Info: Removing owner references for deployment rook-ceph-osd-0
Info: Removed ownerReference for deployment: rook-ceph-osd-0

Info: Removing finalizers from cephclusters/my-cluster
Info: Re-creating the CR cephclusters from dynamic resource
Info: Scaling up the operator
Info: CR is successfully restored. Please watch the operator logs and check the crd
```

2024-01-10 12:01 UTC, parth-gr requested changes

2024-01-10 12:20 UTC, sp98 submitted a review, later dismissed

2024-01-10 15:50 UTC, subhamkrai commented
I see CI is failing with strangely, it passed in the previous run
```
Error: Operation cannot be fulfilled on cephclusters.ceph.rook.io "my-cluster": the object has been modified; please apply your changes to the latest version and try again
```

2024-01-10 17:28 UTC, BlaineEXE commented
> I see CI is failing with strangely, it passed in the previous run
> 
> ```
> Error: Operation cannot be fulfilled on cephclusters.ceph.rook.io "my-cluster": the object has been modified; please apply your changes to the latest version and try again
> ```

This error isn't super concerning in the Kubernetes context, though it can be a bit of a pain to deal with. K8s is often updating resource info in the background in response to **who knows what**. Similar messages appear fairly often in Rook controllers. When it happens in Rook, controllers just reconcile again, and they eventually succeed. 

In a CLI tool, things are a bit trickier because it's harder to "just let the reconcile happen again." 

Here are some options for the Krew plugin in this case. There might be more, but I think these are the big ones:

Option 1: Check if the error is a conflict using `if kerrs.IsConflict(err)`. In this case, we can emit a special error message to the user telling them to retry the command. As a downside, for some CLI commands, that might leave the cluster in a dangling state. For some commands that might be an easy thing, but for long-running commands, that could be very frustrating for users.

Option 2: Check if the error is a conflict (as above), and then re-do the `Get()`-`<update logic>`-`Update()` code flow again. This is do-able, but it's kind of a lot of work to separate out the Get-modify-Update logic, and it's prone to errors. We used to do this more often in Rook but gave up in favor of "just reconcile the whole thing again."

Option 3: (this is the one I'd recommend) Stop using the `Get()`-`<update logic>`-`Update()` pattern, and instead use a `Get()`-<update logic>-`Patch()` pattern. Using `Patch()` tells kubernetes to modify a resource using a very small delta, rather than attempting to update the entirety of the resource. `Patch()` is much less likely to have conflicts because it is only applying that small delta. Rook doesn't use this internally because using `Patch()` inside an operator tends to allow resources to "drift" away from the ideal state after a long period of time. Using `Update()` allows Rook to ensure resources are more likely to be in the desired state compared to `Patch()`.

As a really simple pseudocode example, let's assume I want to add an annotation to a deployment:
```go
dep, err := client.Deployments().Get(name)
if err != nil {
    // failed to find deployment
}
v, ok := dep.Annotations["my-annotation"]
if !ok {
    p := `{"metadata": {"annotations": {"my-annotation": "true"}}`
    err := client.Deployments().Patch(name, p)
    if err != nil {
        // failed to add annotation
    }
}
// annotation already exists on deployment
```

To remove the annotation, I think you can use the same "patch" definition, but you have to do stuff with `"op": "delete"` IIUC: [ref](https://fabianlee.org/2021/09/19/kubernetes-adding-and-removing-pod-template-annotations-using-kubectl/).

-----

Regardless of which option you choose, it is important to note that each one has benefits and drawbacks, and we might not want to always choose the same one for every plugin command. However, I think that the `Patch()` strategy is more likely to yield better results for most CLI tool operations, broadly speaking because it's less likely to return the conflict errors in the first place.

2024-01-11 07:07 UTC, subhamkrai commented on pkg/restore/crd.go
> +	if len(args) == 2 {
we only want the maximum of two args and minimum one arg, One will be `CRD`  and second will be `CRD Name`.

Ex: cephcluster my-cluster, here cephCluster is CRD  and my-cluster CRD Name

2024-01-11 07:08 UTC, subhamkrai commented on pkg/k8sutil/interface.go
>  //go:generate mockgen -package=k8sutil --build_flags=--mod=mod -destination=mocks.go github.com/rook/kubectl-rook-ceph/pkg/k8sutil ClientsetsInterface
This was added by Javier when he added dynamic api. Go mockgen is used to test api client. I found this good read https://thedevelopercafe.com/articles/mocking-interfaces-in-go-with-gomock-670b1a640b00

2024-01-11 07:08 UTC, subhamkrai commented on pkg/restore/crd.go
>  	logging.Info("Backing up kubernetes and crd resources")
removed as we are not  backing in files

2024-01-11 07:09 UTC, subhamkrai commented on pkg/restore/crd.go
> +		logging.Fatal(err)
updated

2024-01-11 07:11 UTC, subhamkrai commented on docs/crd.md
>  Info: Restoring CR my-cluster
That's a valid point, for now, I have not updated the output let's discuss this and then I'll update this.

In my opinion, I liked the idea of not updating the log message but we can keep the last line of the output to give users an idea of a successful command log.

2024-01-11 07:21 UTC, subhamkrai commented
> > I see CI is failing with strangely, it passed in the previous run
> > ```
> > Error: Operation cannot be fulfilled on cephclusters.ceph.rook.io "my-cluster": the object has been modified; please apply your changes to the latest version and try again
> > ```
> 
> This error isn't super concerning in the Kubernetes context, though it can be a bit of a pain to deal with. K8s is often updating resource info in the background in response to **who knows what**. Similar messages appear fairly often in Rook controllers. When it happens in Rook, controllers just reconcile again, and they eventually succeed.
> 
> In a CLI tool, things are a bit trickier because it's harder to "just let the reconcile happen again."
> 
> Here are some options for the Krew plugin in this case. There might be more, but I think these are the big ones:
> 
> Option 1: Check if the error is a conflict using `if kerrs.IsConflict(err)`. In this case, we can emit a special error message to the user telling them to retry the command. As a downside, for some CLI commands, that might leave the cluster in a dangling state. For some commands that might be an easy thing, but for long-running commands, that could be very frustrating for users.
> 
> Option 2: Check if the error is a conflict (as above), and then re-do the `Get()`-`<update logic>`-`Update()` code flow again. This is do-able, but it's kind of a lot of work to separate out the Get-modify-Update logic, and it's prone to errors. We used to do this more often in Rook but gave up in favor of "just reconcile the whole thing again."
> 
> Option 3: (this is the one I'd recommend) Stop using the `Get()`-`<update logic>`-`Update()` pattern, and instead use a `Get()`--`Patch()` pattern. Using `Patch()` tells kubernetes to modify a resource using a very small delta, rather than attempting to update the entirety of the resource. `Patch()` is much less likely to have conflicts because it is only applying that small delta. Rook doesn't use this internally because using `Patch()` inside an operator tends to allow resources to "drift" away from the ideal state after a long period of time. Using `Update()` allows Rook to ensure resources are more likely to be in the desired state compared to `Patch()`.
> 
> As a really simple pseudocode example, let's assume I want to add an annotation to a deployment:
> 
> ```go
> dep, err := client.Deployments().Get(name)
> if err != nil {
>     // failed to find deployment
> }
> v, ok := dep.Annotations["my-annotation"]
> if !ok {
>     p := `{"metadata": {"annotations": {"my-annotation": "true"}}`
>     err := client.Deployments().Patch(name, p)
>     if err != nil {
>         // failed to add annotation
>     }
> }
> // annotation already exists on deployment
> ```
> 
> To remove the annotation, I think you can use the same "patch" definition, but you have to do stuff with `"op": "delete"` IIUC: [ref](https://fabianlee.org/2021/09/19/kubernetes-adding-and-removing-pod-template-annotations-using-kubectl/).
> 
> Regardless of which option you choose, it is important to note that each one has benefits and drawbacks, and we might not want to always choose the same one for every plugin command. However, I think that the `Patch()` strategy is more likely to yield better results for most CLI tool operations, broadly speaking because it's less likely to return the conflict errors in the first place.

Thanks, @BlaineEXE for the great explanation all the suggestions made sense. I agree we have a similar log message in the rook also.

But before I looked at your comment, I working on fixing this issue and found this client-go build retry for updating resources here is the code I added https://github.com/rook/kubectl-rook-ceph/pull/221/files#diff-5552f40f4b7eaad992b1454985dee825a65bf94aab52d9a5b5be488e5114b2ecR99-R102
```go
retryErr := retry.RetryOnConflict(retry.DefaultRetry, func() error {
		_, err := k8sclientset.UpdateResourcesDynamically(ctx, crds.CephRookIoGroup, crds.CephRookResourcesVersion, crd, &crdResource, clusterNamespace)
		return fmt.Errorf("Failed to update resource %q for crd. %v", crName, err)
	})

	if retryErr != nil {
		logging.Fatal(retryErr)
	}
```
I guess we can give it a use, but also I'm completly okay to get more feedback on this and use whatever option we decide.

Thanks @BlaineEXE

2024-01-11 07:49 UTC, parth-gr commented on pkg/restore/crd.go
> +	if len(args) == 2 {
I see I thought we can get list of CRDs

2024-01-11 07:49 UTC, parth-gr commented on pkg/restore/crd.go
> +	if len(args) == 2 {
Maybe a comment on top of it what this arg signifies

2024-01-12 16:05 UTC, BlaineEXE commented
The `RetryOnConflict()` loop helper seems like it would also be a good option. This kube document mentions some of the benefits/drawbacks of patching. A conflict is still possible, even if unlikely, so it's not foolproof.

My broader suggestion is to consider making whichever choice you decide on a pattern in the code to try to avoid the same "class" of error from coming up for other commands.

https://kubernetes.io/docs/reference/using-api/api-concepts/#update-mechanism-json-patch

2024-01-16 13:20 UTC, subhamkrai commented
> The `RetryOnConflict()` loop helper seems like it would also be a good option. This kube document mentions some of the benefits/drawbacks of patching. A conflict is still possible, even if unlikely, so it's not foolproof.
> 
> My broader suggestion is to consider making whichever choice you decide on a code-wide pattern to try to avoid the same "class" of error from coming up for other commands or new commands.
> 
> https://kubernetes.io/docs/reference/using-api/api-concepts/#update-mechanism-json-patch

since your suggestion seems more errorproof, I'll change it to use that. Thanks

2024-01-19 09:26 UTC, subhamkrai commented on docs/crd.md
>  Info: Restoring CR my-cluster
@travisn thoughts?

2024-01-19 21:20 UTC, travisn commented on docs/crd.md
>  Info: Restoring CR my-cluster
I think it is helpful in the docs to show the example output, though when it is long like this, maybe it's less important. If it's simple to grab the output from the CI, maybe we can keep it updated. But if it is a maintenance burden, we can certainly consider shortening it.

2024-01-24 15:36 UTC, BlaineEXE commented on cmd/commands/root.go
> +
nit: blank line in the imports

2024-01-24 17:46 UTC, BlaineEXE approved these changes
lgtm

2024-01-25 13:40 UTC, parth-gr approved these changes

2024-01-25 17:06 UTC, travisn approved these changes

2024-02-02 06:42 UTC, merged