csi: enhance error messages
rook/kubectl-rook-ceph pull request #266
Opened 2024-03-26 13:22 UTC by yati1998

this commit enhances the error message to
give detail info to the users.

2024-03-26 13:37 UTC, subhamkrai commented on pkg/filesystem/subvolume.go
> +				logging.Fatal(fmt.Errorf("Secret data is empty for %q/rook-csi-cephfs-provisioner", clusterNamespace))
@yati1998 please check this, make sense to me aswell

2024-03-26 13:45 UTC, subhamkrai approved these changes

2024-03-26 13:55 UTC, travisn requested changes

2024-03-26 13:55 UTC, travisn commented on pkg/filesystem/subvolume.go
> +				logging.Fatal(fmt.Errorf("Secret data is empty for %v/rook-csi-cephfs-provisioner", clusterNamespace))
`%v` is used when printing a struct or other complex type. If it's just a string, please use `%s` when no quotes are needed. (same for other changes in this PR)
```suggestion
				logging.Fatal(fmt.Errorf("Secret data is empty for %s/rook-csi-cephfs-provisioner", clusterNamespace))
```

2024-03-26 14:00 UTC, travisn approved these changes

2024-03-26 15:09 UTC, subhamkrai requested changes
@yati1998 please check the CI issues. Thanks

2024-03-26 15:15 UTC, Madhu-1 commented on pkg/filesystem/subvolume.go
> +				logging.Fatal(fmt.Errorf("Secret data is empty for %s/rook-csi-cephfs-provisioner", clusterNamespace))
```suggestion
logging.Fatal(fmt.Errorf("Secret data is empty for %s/%s", clusterNamespace,scList.Items[i].ObjectMeta.Name))
```

2024-03-26 15:30 UTC, Madhu-1 approved these changes

2024-03-27 03:32 UTC, subhamkrai approved these changes

2024-03-27 03:32 UTC, merged