Add rados commands
rook/kubectl-rook-ceph pull request #270
Opened 2024-04-02 08:46 UTC by OdedViner

**Description of your changes:**

**Which issue is resolved by this Pull Request:**
Resolves #

**Checklist:**

- [ ] **Commit Message Formatting**: Commit titles and messages follow guidelines in the [developer guide](https://rook.io/docs/rook/latest/Contributing/development-flow/#commit-structure).
- [ ] Reviewed the developer guide on [Submitting a Pull Request](https://rook.io/docs/rook/latest/Contributing/development-flow/#submitting-a-pull-request)
- [ ] CI tests has been updated, if necessary.
- [ ] Documentation has been updated, if necessary.
- [ ] Unit tests have been added, if necessary.

2024-04-02 10:47 UTC, subhamkrai requested changes
please update commit structure https://github.com/rook/rook/blob/master/Documentation/Contributing/development-flow.md#commit-structure

2024-04-02 10:50 UTC, Madhu-1 commented on cmd/commands/rados.go
> +Copyright 2023 The Rook Authors. All rights reserved.
2024?

2024-04-02 11:52 UTC, subhamkrai commented
> please update commit structure https://github.com/rook/rook/blob/master/Documentation/Contributing/development-flow.md#commit-structure

@OdedViner ^^

2024-04-04 04:33 UTC, subhamkrai requested changes
you also need to add docs changes in https://github.com/rook/kubectl-rook-ceph/blob/master/README.md#commands and https://github.com/rook/kubectl-rook-ceph/blob/master/README.md#documentation

2024-04-04 09:18 UTC, OdedViner commented
> you also need to add docs changes in https://github.com/rook/kubectl-rook-ceph/blob/master/README.md#commands and https://github.com/rook/kubectl-rook-ceph/blob/master/README.md#documentation

Done

2024-04-04 09:27 UTC, subhamkrai commented
> > you also need to add docs changes in https://github.com/rook/kubectl-rook-ceph/blob/master/README.md#commands and https://github.com/rook/kubectl-rook-ceph/blob/master/README.md#documentation
> 
> Done

you missed adding the  https://github.com/rook/kubectl-rook-ceph/blob/master/README.md#documentation

2024-04-04 09:28 UTC, subhamkrai requested changes

2024-04-04 09:39 UTC, OdedViner commented on .github/workflows/go-test.yaml
> +      - name: Rados df using context
done

2024-04-04 10:54 UTC, subhamkrai approved these changes

2024-04-04 11:07 UTC, Madhu-1 approved these changes

2024-04-04 11:07 UTC, merged