delete nfs config for stale subvolume
rook/kubectl-rook-ceph pull request #302
Opened 2024-06-19 10:53 UTC by yati1998

this commit deletes the nfs config entry for
the stale subvolume

Resolves: #272

2024-06-20 08:10 UTC, nixpanic commented on pkg/filesystem/subvolume.go
> +		logging.Info("No PV found for subvolume %s: %s", subVol, err)
this message looks incorrect

2024-06-20 08:13 UTC, nixpanic commented on pkg/filesystem/subvolume.go
> +	nfscluster, err := runCommand(ctx, clientsets, OperatorNamespace, CephClusterNamespace, cmd, args)
`nfscluster` should probably be `exportList` or something

2024-06-20 08:13 UTC, nixpanic commented on pkg/filesystem/subvolume.go
> +	var nfsCluster string
these variables are incorrecly named too, it is about exports, not clusters in this function

2024-06-20 08:15 UTC, nixpanic commented on pkg/filesystem/subvolume.go
> +				logging.Fatal(err, "failed to delete export for subvol %q", subVol)
maybe mention nfsCLuster+export so that users have a little more guidance?

2024-06-20 08:33 UTC, Madhu-1 commented on pkg/filesystem/subvolume.go
> +	errc := json.Unmarshal([]byte(nfscluster), &unmarshalcluster)
use err =

2024-06-20 08:33 UTC, Madhu-1 commented on pkg/filesystem/subvolume.go
> +		fmt.Println("Error:", errc)
use logger instead of Println

2024-06-20 08:33 UTC, Madhu-1 commented on pkg/filesystem/subvolume.go
> +	}
i think we dont need else part here.

2024-06-24 10:01 UTC, Madhu-1 commented on pkg/filesystem/subvolume.go
> +			logging.Info("export path not found")
log subvolume and nfsClusterName here

2024-06-24 10:01 UTC, Madhu-1 commented on pkg/filesystem/subvolume.go
> +		logging.Info("Nfs cluster not found for subvolume %s: %s", subVol, err)
log the poolName as well.

2024-06-24 11:40 UTC, Madhu-1 approved these changes
LGTM

2024-06-24 11:40 UTC, Madhu-1 commented on pkg/filesystem/subvolume.go
> +		logging.Fatal(fmt.Errorf("pool name not found: %q", err))
log the pool name as well .

2024-06-24 11:46 UTC, subhamkrai requested changes
small nit

2024-06-24 11:46 UTC, subhamkrai commented on pkg/filesystem/subvolume.go
> +		logging.Info("Nfs cluster not found for subvolume %s: %s %s", subVol, poolName, err)
```suggestion
		logging.Info("nfs cluster not found for subvolume %s: %s %s", subVol, poolName, err)
```

2024-06-24 13:47 UTC, nixpanic approved these changes

2024-06-24 15:43 UTC, subhamkrai approved these changes

2024-06-24 15:45 UTC, merged