build: update Go and K8s api version
rook/kubectl-rook-ceph pull request #310
Opened 2024-07-11 11:04 UTC by ShravaniVangur

The commit updates the version of Go from 1.21 to 1.22.0  and updates the Kubernetes api versions accordingly. 

Resolves #309

2024-07-11 11:58 UTC, Madhu-1 commented on go.mod
> +	k8s.io/client-go v0.30.2
This also needs to be changed in go.sum as well, i don't see that, did you run `go mod tidy` after updating these values?

2024-07-11 11:58 UTC, Madhu-1 commented on .github/workflows/set-up-go/action.yaml
> +        go-version: "1.22.0"
@subhamkrai how about updating this to use go.mod so that we don't need to change in multiple places?

2024-07-11 12:29 UTC, subhamkrai requested changes
@ShravaniVangur  you need to sign-off your changes you can read here https://rook.github.io/docs/rook/latest/Contributing/development-flow/#commit-structure

2024-07-16 07:21 UTC, subhamkrai commented
> @ShravaniVangur you need to sign-off your changes you can read here https://rook.github.io/docs/rook/latest/Contributing/development-flow/#commit-structure



> @ShravaniVangur you need to sign-off your changes you can read here https://rook.github.io/docs/rook/latest/Contributing/development-flow/#commit-structure

@ShravaniVangur can you please fix the CI error thanks

2024-07-17 10:52 UTC, subhamkrai approved these changes

2024-07-17 10:52 UTC, merged